export declare const ENC_MAGIC: string;
export declare const BACKUP_MAGIC: string;
export declare function deriveKey(password: string, salt: Buffer): Buffer;
export declare function encryptJSON(value: any, password: string): string;
export declare function decryptJSON(payload: string, password: string): any;
export declare function isEncryptedPayload(value: any): boolean;
export declare function useEncryptedFileAuthState(folder: string, opts: { password: string; logger?: any }): Promise<{ state: any; saveCreds: () => Promise<void> }>;
export declare function useEncryptedSingleFileAuthState(file: string, opts: { password: string; logger?: any }): Promise<{ state: any; saveCreds: () => Promise<void> }>;
export declare function backupAuthState(src: string, outFile: string, opts?: { password?: string }): Promise<any>;
export declare function restoreAuthState(backupFile: string, dest: string, opts?: { password?: string; single?: boolean }): Promise<any>;
export declare function writeAuthIntegrity(folder: string, opts?: { secret?: string }): Promise<any>;
export declare function verifyAuthIntegrity(folder: string, opts?: { secret?: string }): Promise<any>;
export declare function repairAuthState(folder: string, opts?: { password?: string; backupFile?: string; backupPassword?: string; logger?: any }): Promise<any>;
export declare function createRateLimiter(opts?: { max?: number; windowMs?: number; minIntervalMs?: number; now?: () => number }): any;
export declare function withPairingGuard<T = any>(sock: T, opts?: { maxPerHour?: number; globalMaxPerHour?: number; minIntervalMs?: number; logger?: any; now?: () => number }): T;
export declare function createQRGuard(opts?: { ttlMs?: number; now?: () => number; onFirst?: (qr: string) => void; onBlocked?: (qr: string) => void }): any;
export declare function redactSecrets(value: any, opts?: { extraKeys?: string[]; maxDepth?: number }): any;
export declare function secureLogger(base: any, opts?: { extraKeys?: string[] }): any;
export declare function secureLogout(sock: any, opts?: { authFolder?: string; authFile?: string; passes?: number; logger?: any }): Promise<any>;
